[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vault_pool = "7fhJ2K7sem2rZLXchD1JM65k1M2ytisYn8xvgeN6LHEP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/noobmdev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
